flowchart TD
    incomingRequest(Start)-->|HTTP request to https://api.thinksolar.co.nz|app(App Entry Point)
    app-->|If path is valid, Laravel router passes request to applicable middleware.|middleware(Middleware)
    middleware-->|If middleware layer permits, route handler forwards request to controller.|success(Controller)